name: Synchronize dtinth-water.css
on:
  push:
    branches:
      - main
      - deployment-test/dtinth-water
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        repository: dtinth/dtinth-water
        ssh-key: ${{ secrets.WATER_DEPLOY_KEY }}
        path: water
      - run: cp assets/dtinth-water.css water
      - name: Some Git wizardry
        run: |
          cd water
          git add --all \
            && git commit -m "Synchronize with https://github.com/dtinth/notes.dt.in.th/commit/${GITHUB_SHA::8}" \
            || echo "Nothing to commit"
          git push
        env:
          GIT_COMMITTER_NAME: dtinth-bot
          GIT_AUTHOR_NAME: dtinth-bot
          EMAIL: dtinth-bot@users.noreply.github.com
